### PR TITLE
Missing Ability specs on Comments.

### LINKED ISSUE #200: Add missing spec for recent comment edition auth
Recent comment edition was introduced in #195 to fix #108, but the test suite isn't explicit about it (the spec tests the controller's `edit` action).

Add either a controller (integration) spec for this, or a spec on `Ability`.

### PR DESCRIPTION
**Pull request by zsombor**
@mezis here are your Ability specs on Comments, fixes #200. My previous #108 did not add any new ability constraints having merely reused the existing code that turned out to be untested.  

I feel that adding tests on a lower model level is generally preferable to integration or controller specs. Especially when possible :-)

### CODE REVIEW

**Comment by mezis** [comment]
:+1: and thanks for the reference to Joseph Fourier!

> existing code that turned out to be untested

I'm definitely to blame here. Shouldn't have written most of this in such a hurry ^_^

**Comment by zsombor** [comment]
OOPS I broke the build on Travis. Seems to work fine locally. Will look into this before closing.

**Comment by mezis** [comment]
Ah, the downside of using fixtures. I'll wait for the build to merge.

**Comment by mezis** [comment]
Thanks @zsombor!

**Pull request merged**
