### PR TITLE
[Fixes #198] Add strong params to search controller

### LINKED ISSUE #198: Search: add strong parameters to controller.

### PR DESCRIPTION
**Pull request by HashNuke**

### CODE REVIEW

**Comment by mezis** [comment]
Thanks! No test coverage though, so I'll massage this PR a bit before merging.

**Comment by HashNuke** [comment]
@mezis Thank you.

I noticed that `features/ideas/search.feature` already tests for it. So I skipped writing any. Do let me know if you have anything in mind tho.

**Comment by thejspr** [comment]
I think the cucumber test is sufficient coverage for this, merging

**Comment by mezis** [comment]
I don't :)

Behaviour changed but tests didn't, which is the first smell: there should
have been at least one (controller) spec to cover parameters in my opinion
-- and that would break without strong params.

Yes, it's "covered" by a cuke, but it's not tested. Cukes are for
acceptance (in appfab at least), and in my opinion cukes don't replace the
need for unit/functional tests.

## 

-- Julien Letessier

**Comment by thejspr** [comment]
Sorry I jumped the gun on merging this. I still think more testing is
overkill though :)

It would be testing implementation as the behaviour has not changed, only
one parameter would be passed to the search object

## 

Jesper Kjeldgaard

On 24 May 2014, at 09:57, Julien Letessier notifications@github.com wrote:

I don't :)

Behaviour changed but tests didn't, which is the first smell: there should
have been at least one (controller) spec to cover parameters in my opinion
-- and that would break without strong params.

Yes, it's "covered" by a cuke, but it's not tested. Cukes are for
acceptance (in appfab at least), and in my opinion cukes don't replace the
need for unit/functional tests.

## 

-- Julien Letessier

—
Reply to this email directly or view it on
GitHubhttps://github.com/mezis/appfab/pull/210#issuecomment-44081788
.

**Comment by mezis** [comment]
> It would be testing implementation as the behaviour has not changed, only
> one parameter would be passed to the search object

I was trying to think of something that would pass before and break with this code in to prove you wrong, but I can't ... so I'll shut up now ^_^

(still uncomfortable we don't have controller tests for this, but hey, I'm largely to blame)

**Pull request merged**
